apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmdb
  namespace: techmpoc01
  labels:
    app: database
    version: 12.2.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 12.2.0.1
  template:
    metadata:
      name: database
      labels:
        app: database
        version: 12.2.0.1
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: ora-data
        persistentVolumeClaim:
          claimName: ora-data
      containers:
      - name: database
        command:
        - /home/oracle/setup/dockerInit.sh
        image: container-registry.oracle.com/database/enterprise:12.2.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 8Gi
        ports:
        - containerPort: 1521
          hostPort: 1521
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - name: ora-data
            mountPath: "/opt/oracle/oradata"
        env:
          - name: DB_SID
            value: OSM
          - name: DB_PDB
            value: OSMPDB1
          - name: DB_PASSWD
            value: 1zm9Kz0jr#A#
          - name: DB_DOMAIN
            value: my.domain.com
          - name: DB_BUNDLE
            value: basic
          - name: DB_MEMORY
            value: 8g
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: techmpoc01
spec:
  selector:
    app: database
    version: 12.2.0.1
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
