---
- hosts: master
  user: rana
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  vars_files:
      - mysecrets.yml


  tasks:
           

   - name: Create a k8s namespace
     command: kubectl create namespace techmpoc01

   - name: Create docker secret
     command: kubectl create secret docker-registry regsecret --docker-server=container-registry.oracle.com --docker-username="{{user}}" --docker-password="{{pass}}" --docker-email="{{email}}" -n techmpoc01

   - name: Copy the database yaml file
     copy:
        src: /opt/ansible/{{ item }}
        dest: /var/tmp/
        mode: 0777
     with_items:
       - pv-pvc.yaml
       - database.yml

   - name: Create the PV and PVC volumes
     command: kubectl create -f /var/tmp/pv-pvc.yaml

   - name: Create the database and service
     command: kubectl create -f /var/tmp/database.yml
